version: '3'
services:
  db:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: nest-pokedex
    volumes:
      - ./mongo:/data/db 